### ISSUE TITLE
当心被ban

### ISSUE THREAD

**Issue by tim1103** [rain15z3/luogu-info#1]
最近洛谷日爆比较严重，如果没对访问洛谷服务器的频率进行限制，容易导致封号+程序被ban，建议改进。

**Comment by rain15z3** [comment]
我这个用的不是洛谷服务器，只是动态生成的图片

**Comment by rain15z3** [comment]
谢谢，大概30分钟爬一次应该不要紧吧？

**Comment by rain15z3** [comment]
改成两个小时了，炒鸡担心QAQ

**Comment by tim1103** [comment]
> 改成两个小时了，炒鸡担心QAQ

理论上6小时同步一次，例如清华大学开源镜像站就是6小时同步一次
